version: '2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka

  db_admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
     - db:db
    ports:
      - "8080:80"

  omeka:
    depends_on:
      - db
    image: klokantech/omeka-docker
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/plugins/Iiif/
    restart: always

